# namePrefix -- Prefix to append before resource names
namePrefix: ""

# constraints -- Constraints to create
constraints: []
  #- kind: k8srequiredannotations
  #  name: foobar
  #  parameters:
  #    annotations:
  #      - key: "foo"
  #        allowedRegex: "bar"
