{{- $kinds := list }}
{{- range .Values.constraints  }}
{{ $kinds = append $kinds .kind }}
{{- end }}

apiVersion: v1
kind: ServiceAccount
metadata:
  name: wait-for-crds
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wait-for-crds
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wait-for-crds
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: wait-for-crds
subjects:
- kind: ServiceAccount
  name: wait-for-crds
  namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: wait-for-crds
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded,hook-failed"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 0
      serviceAccountName: wait-for-crds
      containers:
      - name: wait-for-crds
        image: bitnami/kubectl:1.23.5-debian-10-r30@sha256:d0e24ae78c1f70fa347b5ca9518d91d9a65a29ca8e38e936123746f4d70b9cdb
        command: ["sh", "-c", "timeout 3m bash -c 'until kubectl get crd {{ range $kinds | uniq }}{{ (lower .) }}.constraints.gatekeeper.sh {{ end }}; do sleep 1; done'"]
