namePrefix: ""
constraints: []
  #- kind: K8sRequiredAnnotations
  #  name: foobar
  #  parameters:
  #    annotations:
  #      - key: "foo"
  #        allowedRegex: "bar"

exclude:
  - excludedNamespaces: ["kube-system", "gatekeeper-system"]
    processes: ["*"]
