apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: secretsstorecsiuniquevolume
spec:
  crd:
    spec:
      names:
        kind: SecretsStoreCSIUniqueVolume
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |-
        package secretsstorecsiuniquevolume

        violation[{"msg": msg}] {
        	volumes := input.review.object.spec.volumes
        	count(volumes) > 0
        	volume := volumes[_]
        	volume.csi.driver = "secrets-store.csi.k8s.io"

        	# converts list into set, which requires unique values
        	uniqueNames := {x | x = volume.name}
        	count(volumes) != count(uniqueNames)
        	msg := sprintf(`'%v' has to specify a serviceAccountName`, [input.review.kind.kind])
        }
