apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredAnnotations
metadata:
  name: ingress-class
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: [""]
  parameters:
    message: "Resource does not contain the required annotation"
    annotations: []
