{{- range .Values.constraints }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
spec:
  enforcementAction: {{ .enforcementAction | default "deny" }}
  match: {{- toYaml .match | default (include "gatekeeper-library.defaultMatch" .)  | nindent 4 }}
  {{- with .parameters }}
  parameters: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
