name: e2e
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.5.0
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: "v3.4.1"
      - name: Run e2e tests
        run: |
          make e2e
