name: kustomize
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install kustomize
        run: |
          wget -q https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.0.1/kustomize_v4.0.1_linux_amd64.tar.gz
          tar xzf kustomize_v4.0.1_linux_amd64.tar.gz
          rm kustomize_v4.0.1_linux_amd64.tar.gz
          sudo mv kustomize /bin/kustomize
      - name: Checkout
        uses: actions/checkout@master
      - name: Run Kustomize build
        run: |
          kustomize build ./deploy
