apiVersion: constraints.gatekeeper.sh/v1beta1
kind: FluxDisableCrossNamespaceSource
metadata:
  name: disable-cross-namespace-source
spec:
  match:
    kinds:
      - apiGroups: ["helm.toolkit.fluxcd.io"]
        kinds: ["HelmRelease"]
      - apiGroups: ["kustomize.toolkit.fluxcd.io"]
        kinds: ["Kustomization"]
    excludedNamespaces:
      - "flux-system"
